name: 🐛 Bug Report
description: Report a bug in FL-GO
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please ensure you've completed these steps before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have run the validation script (`make validate`) to confirm FL-GO is properly set up
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Aggregator (Sync FL)
        - Aggregator (Async FL)
        - Collaborator
        - CLI Commands
        - Docker
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Please paste any relevant log output or error messages
      render: shell
      placeholder: Paste logs here...

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux (Ubuntu)
        - Linux (Other)
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Windows
        - Docker
        - Other
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using?
      placeholder: "1.22.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.11.0"
    validations:
      required: true

  - type: input
    id: fl-go-version
    attributes:
      label: FL-GO Version
      description: What version of FL-GO are you using?
      placeholder: "v1.0.0 or commit hash"
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please share your plan.yaml configuration (remove any sensitive information)
      render: yaml
      placeholder: |
        mode: "sync"
        rounds: 3
        # ... rest of config

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here (screenshots, related issues, etc.)
      placeholder: Any additional information that might be helpful...
