name: 🚀 Feature Request
description: Suggest a new feature for FL-GO
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please ensure you've completed these steps before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have read the documentation to ensure this feature doesn't already exist
          required: true
        - label: This feature aligns with the goals of FL-GO (federated learning in Go)
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - FL Algorithm (new aggregation method)
        - FL Mode (sync/async improvements)
        - CLI Enhancement
        - Performance Optimization
        - Security Enhancement
        - Documentation
        - Testing/Validation
        - DevOps/CI
        - Integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe alternatives you've considered
      placeholder: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low (nice to have)
        - Medium (would improve workflow)
        - High (blocking current work)
        - Critical (major limitation)
    validations:
      required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Willingness
      description: Are you willing to help implement this feature?
      options:
        - label: I would like to implement this feature myself
        - label: I can help with testing the implementation
        - label: I can help with documentation
        - label: I can provide feedback during development

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: |
        Who would benefit from this feature?
        How would it be used?
        What workflows would it improve?

  - type: textarea
    id: technical-details
    attributes:
      label: Technical Details
      description: Any technical considerations or implementation details
      placeholder: |
        - API changes needed
        - Configuration options
        - Performance considerations
        - Compatibility requirements

  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Provide examples of how this feature would work
      placeholder: |
        Code examples, configuration samples, or command-line usage examples

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to papers, other implementations, or related work
      placeholder: |
        - Research papers
        - Similar implementations
        - Relevant standards or specifications

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request
      placeholder: Any additional information that might be helpful...
