rounds: 3
collaborators:
  - id: "collab1"
    address: "localhost:50052"
  - id: "collab2"
    address: "localhost:50053"
aggregator:
  address: "localhost:50051"
initial_model: "models/init_model.pt"
output_model: "models/aggregated_model.pt"
tasks:
  train:
    script: "scripts/train.py"
    args:
      epochs: 1
      batch_size: 32
