# Synchronous Federated Learning Configuration
mode: "sync"  # Options: "sync" or "async"
rounds: 3

# Algorithm configuration (optional - defaults to fedavg)
algorithm:
  name: "fedavg"
  hyperparameters: {}
collaborators:
  - id: "collab1"
    address: "localhost:50052"
  - id: "collab2"
    address: "localhost:50053"
aggregator:
  address: "localhost:50051"
initial_model: "models/init_model.pt"
output_model: "models/aggregated_model.pt"
tasks:
  train:
    script: "scripts/train.py"
    args:
      epochs: 1
      batch_size: 32

# Async-specific configuration (used when mode: "async")
async_config:
  max_staleness: 300      # Maximum staleness in seconds (5 minutes)
  min_updates: 1          # Minimum updates before aggregation
  aggregation_delay: 10   # Delay in seconds before aggregating
  staleness_weight: 0.95  # Weight decay factor for stale updates (0.95^staleness)
