// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/federation.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollaboratorId string                 `protobuf:"bytes,1,opt,name=collaborator_id,json=collaboratorId,proto3" json:"collaborator_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_api_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_api_federation_proto_rawDescGZIP(), []int{0}
}

func (x *JoinRequest) GetCollaboratorId() string {
	if x != nil {
		return x.CollaboratorId
	}
	return ""
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialModel  []byte                 `protobuf:"bytes,1,opt,name=initial_model,json=initialModel,proto3" json:"initial_model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_api_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_api_federation_proto_rawDescGZIP(), []int{1}
}

func (x *JoinResponse) GetInitialModel() []byte {
	if x != nil {
		return x.InitialModel
	}
	return nil
}

type ModelUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollaboratorId string                 `protobuf:"bytes,1,opt,name=collaborator_id,json=collaboratorId,proto3" json:"collaborator_id,omitempty"`
	ModelWeights   []byte                 `protobuf:"bytes,2,opt,name=model_weights,json=modelWeights,proto3" json:"model_weights,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelUpdate) Reset() {
	*x = ModelUpdate{}
	mi := &file_api_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelUpdate) ProtoMessage() {}

func (x *ModelUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_api_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelUpdate.ProtoReflect.Descriptor instead.
func (*ModelUpdate) Descriptor() ([]byte, []int) {
	return file_api_federation_proto_rawDescGZIP(), []int{2}
}

func (x *ModelUpdate) GetCollaboratorId() string {
	if x != nil {
		return x.CollaboratorId
	}
	return ""
}

func (x *ModelUpdate) GetModelWeights() []byte {
	if x != nil {
		return x.ModelWeights
	}
	return nil
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_api_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_api_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_api_federation_proto_rawDescGZIP(), []int{3}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_federation_proto protoreflect.FileDescriptor

const file_api_federation_proto_rawDesc = "" +
	"\n" +
	"\x14api/federation.proto\x12\n" +
	"federation\"6\n" +
	"\vJoinRequest\x12'\n" +
	"\x0fcollaborator_id\x18\x01 \x01(\tR\x0ecollaboratorId\"3\n" +
	"\fJoinResponse\x12#\n" +
	"\rinitial_model\x18\x01 \x01(\fR\finitialModel\"[\n" +
	"\vModelUpdate\x12'\n" +
	"\x0fcollaborator_id\x18\x01 \x01(\tR\x0ecollaboratorId\x12#\n" +
	"\rmodel_weights\x18\x02 \x01(\fR\fmodelWeights\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x92\x01\n" +
	"\x11FederatedLearning\x12C\n" +
	"\x0eJoinFederation\x12\x17.federation.JoinRequest\x1a\x18.federation.JoinResponse\x128\n" +
	"\fSubmitUpdate\x12\x17.federation.ModelUpdate\x1a\x0f.federation.AckB\aZ\x05./apib\x06proto3"

var (
	file_api_federation_proto_rawDescOnce sync.Once
	file_api_federation_proto_rawDescData []byte
)

func file_api_federation_proto_rawDescGZIP() []byte {
	file_api_federation_proto_rawDescOnce.Do(func() {
		file_api_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_federation_proto_rawDesc), len(file_api_federation_proto_rawDesc)))
	})
	return file_api_federation_proto_rawDescData
}

var file_api_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_federation_proto_goTypes = []any{
	(*JoinRequest)(nil),  // 0: federation.JoinRequest
	(*JoinResponse)(nil), // 1: federation.JoinResponse
	(*ModelUpdate)(nil),  // 2: federation.ModelUpdate
	(*Ack)(nil),          // 3: federation.Ack
}
var file_api_federation_proto_depIdxs = []int32{
	0, // 0: federation.FederatedLearning.JoinFederation:input_type -> federation.JoinRequest
	2, // 1: federation.FederatedLearning.SubmitUpdate:input_type -> federation.ModelUpdate
	1, // 2: federation.FederatedLearning.JoinFederation:output_type -> federation.JoinResponse
	3, // 3: federation.FederatedLearning.SubmitUpdate:output_type -> federation.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_federation_proto_init() }
func file_api_federation_proto_init() {
	if File_api_federation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_federation_proto_rawDesc), len(file_api_federation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_federation_proto_goTypes,
		DependencyIndexes: file_api_federation_proto_depIdxs,
		MessageInfos:      file_api_federation_proto_msgTypes,
	}.Build()
	File_api_federation_proto = out.File
	file_api_federation_proto_goTypes = nil
	file_api_federation_proto_depIdxs = nil
}
